<a href="https://colab.research.google.com/github/dipta007/notes/blob/master/programming/python/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [2]:
np.array([1, 2, 3])

array([1, 2, 3])

In [3]:
np.array([[1,2,3], [4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [6]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [8]:
np.linspace(0, 10, 100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [9]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [10]:
np.random.rand(5)

array([0.49959319, 0.57236635, 0.60776666, 0.46778974, 0.37957224])

UniForm Distribution

In [11]:
np.random.rand(4, 5)

array([[0.09507571, 0.37896453, 0.75596129, 0.1675309 , 0.13948902],
       [0.44176153, 0.49727779, 0.18242551, 0.27958741, 0.74007361],
       [0.12133105, 0.61269626, 0.06354361, 0.17057507, 0.84423067],
       [0.97149378, 0.31438118, 0.08819729, 0.91071947, 0.27137467]])

Standard Distribution

In [12]:
np.random.randn(4, 5)

array([[ 1.3965432 , -0.29313571, -1.10230074,  0.19255068,  1.50698145],
       [ 0.58230431,  1.29430087, -0.07718834, -1.4483013 , -0.51262789],
       [ 0.34057566,  0.04136714, -0.50253171,  0.18355537, -1.35387815],
       [-0.02622768,  2.01311937,  0.15169399,  1.14640205,  0.04955429]])

In [13]:
np.random.randint(0, 100, 10)

array([82, 41, 66, 15, 38, 11, 95, 51,  5, 66])

In [0]:
arr = np.arange(0, 10)

In [15]:
arr.reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [16]:
arr.max()

9

In [17]:
arr.min()

0

In [18]:
arr.argmax()

9

In [19]:
arr.argmin()

0

In [20]:
arr.shape

(10,)

In [21]:
arr.dtype

dtype('int64')

In [0]:
arr = np.arange(0, 11)

In [23]:
arr[0], arr[:6], arr[2:3]

(0, array([0, 1, 2, 3, 4, 5]), array([2]))

In [0]:
arr_copy = arr.copy()

In [0]:
arr_2d = np.array([[1, 2], [3, 4], [5, 6]])

In [28]:
arr_2d

array([[1, 2],
       [3, 4],
       [5, 6]])

In [30]:
arr_2d[2, 1], arr_2d[2][1]

(6, 6)