<a href="https://colab.research.google.com/github/dipta007/notes/blob/master/programming/python/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [2]:
np.array([1, 2, 3])

array([1, 2, 3])

In [3]:
np.array([[1,2,3], [4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [9]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [11]:
np.linspace(0, 10, 100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [12]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [15]:
np.random.rand(5)

array([0.7687473 , 0.30219395, 0.60839081, 0.59808154, 0.43741921])

UniForm Distribution

In [17]:
np.random.rand(4, 5)

array([[0.81419321, 0.49936068, 0.73982105, 0.52083868, 0.81340854],
       [0.60426844, 0.54006347, 0.04071946, 0.13313507, 0.17787709],
       [0.32376572, 0.52671614, 0.26783698, 0.11604393, 0.29513977],
       [0.08142433, 0.5892429 , 0.80485558, 0.52354586, 0.37861522]])

Standard Distribution

In [19]:
np.random.randn(4, 5)

array([[ 1.89451194, -1.41592784,  0.39539341,  0.39485467,  0.88194138],
       [-1.36430202, -0.70333059,  1.01505124, -0.72439303,  1.47409897],
       [ 0.11813932, -1.2260674 , -0.91930942,  0.15722283, -0.05229562],
       [ 0.78749491,  2.03970955, -1.8420705 ,  0.89384271,  1.12544118]])

In [21]:
np.random.randint(0, 100, 10)

array([51, 63,  2, 53, 76, 26, 16, 80, 94,  4])

In [0]:
arr = np.arange(0, 10)

In [24]:
arr.reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [25]:
arr.max()

9

In [26]:
arr.min()

0

In [27]:
arr.argmax()

9

In [28]:
arr.argmin()

0

In [29]:
arr.shape

(10,)

In [30]:
arr.dtype

dtype('int64')